export const FETCH_USER = 'FETCH_USER';
export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_NOTFOUND = 'FETCH_NOTFOUND';
export const SET_RESUME_ACTIVE = 'SET_RESUME_ACTIVE';
export const SET_FORMTAB_ACTIVE = 'SET_FORMTAB_ACTIVE';
export const POST_RESUME = 'POST_RESUME';
